baseurl = "http://michal.papierski.net/"
title = "Michał Papierski's Blog"
languageCode = "en-us"
theme = "hugo_theme_robust"

# For source code syntax highlighting
pygmentsuseclasses = true
pygmentsstyle = "monokai"
PygmentsCodeFences = true

[Params]
  Author = "Michał Papierski"

# Disqus stuff
disqusShortname = "michalpapierskisblog"
