baseurl = "http://michal.papierski.net/"
title = "Michał Papierski's Blog"
languageCode = "en-us"
theme = "hyde-x"

# For source code syntax highlighting
[Params]
  Author = "Michał Papierski"
  highlight = "sunburst"
  github = "https://github.com/mpapierski"
  rss = true

# Disqus stuff
disqusShortname = "michalpapierskisblog"
