baseurl = "http://michal.papierski.net/"
title = "Michał Papierski"
languageCode = "en-us"
theme = "hyde"
copyright = "Michał Papierski"

googleAnalytics = "UA-22624843-1"

[Author]
	name = "Michał Papierski"

[params]
	description = "stuff written by me"
	github = "https://github.com/mpapierski"
	disqus = "michalpapierskisblog"
